name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        java: [17-jdk, 20-jdk]
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: ./gradlew build

      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/